org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Optimizaciones adicionales para evitar errores de memoria
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=true
